# Generated by Django 2.2 on 2019-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191006_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Fruits'), ('SW', 'Spices'), ('OW', 'Vegetables')], max_length=2),
        ),
    ]
